### ISSUE TITLE
关于地图初次载入时的背景色

### ISSUE THREAD

**Issue by CNFeffery** [plainheart/echarts-extension-amap#25]
大佬你好，我想咨询一下在地图初次载入时，会有一个灰白色的背景闪一下就会刷掉，但是对应暗色地图时观感不太好：
![image](https://user-images.githubusercontent.com/49147660/121475908-9abbbf80-c9f8-11eb-9f83-50a8b6c96716.png)
载入后是这样的：
![image](https://user-images.githubusercontent.com/49147660/121475950-a7d8ae80-c9f8-11eb-9791-46a9b45fd95b.png)

请问这个背景色有没有办法进行修改，我翻了高德地图的文档暂时没有收获😔

**Comment by plainheart** [comment]
```css
.amap-container {
  background: none !important;
}
```
